name: Docker Push

on:
    push:
        branches:
            - develop # develop 브랜치에 푸시할 때 실행

jobs:
    docker-push:
        runs-on: [self-hosted, Linux, X64, ubuntu, i7]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Add user to docker group
              run: |
                  sudo usermod -aG docker $USER
                  newgrp docker

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  image: tonistiigi/binfmt:latest
                  platforms: all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login Dockerhub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            - name: Build and push Docker image
              run: |
                  docker buildx create --use
                  docker buildx build --platform linux/amd64,linux/arm64 -t stevenkais/kinest1997:vapor --push .
