name: Docker Push

on:
  push:
    branches:
      - develop  # develop 브랜치에 푸시할 때 실행

jobs:
  docker-push:
    runs-on: [self-hosted, Linux, X64, ubuntu, i7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        run: |
          sudo docker buildx build --platform linux/arm64 -t stevenkais/kinest1997:vapor --push .
